import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CARDS,player,room,start,act,view,play,timeout,chooseBotMove,uid} from '../web/engine.js';
function fixture(n=4,mode='ffa'){
 const s=room('ABC234',mode,player('P0','key0',0));
 for(let i=1;i<n;i++){const p=player('P'+i,'key'+i,mode==='teams'?i%2:0);p.ready=true;s.players.push(p)}
 start(s,1000);s.turn=0;s.phase='play';s.players.forEach(p=>{p.total=20;p.revealed=true});return s;
}
function card(s,type){const c={id:uid(),type};s.players[s.turn].hand=[c];s.phase='play';return c.id}
test('deck has all 76 cards and independent private hands',()=>{const s=fixture(8);assert.equal(s.deck.length,36);assert.equal(new Set(s.players.flatMap(p=>p.hand.map(c=>c.id))).size,40);for(const p of s.players){const v=view(s,p.id);assert.equal(v.players.filter(x=>'hand'in x).length,1);assert.equal(v.players.find(x=>x.id===p.id).hand.length,5);assert.ok(!JSON.stringify(v).includes('key0'));assert.ok(!('deck'in v));assert.ok(!('requests'in v))}});
test('initial totals are 20–30, hidden until the first turn',()=>{const s=room('ABC234','ffa',player('One','one'));const p=player('Two','two');p.ready=true;s.players.push(p);start(s);for(const p of s.players)assert.ok(p.total>=20&&p.total<=30);const v=view(s,s.players[s.turn].id);assert.equal(v.players.filter(p=>p.total===null).length,1)});
test('exact zero wins immediately',()=>{const s=fixture();const p=s.players[0];p.total=3;play(s,p.id,card(s,'minus3'),p.id);assert.equal(s.status,'finished');assert.deepEqual(s.winners,[p.id])});
test('negative eliminates and next turn skips eliminated player',()=>{const s=fixture();s.players[1].total=2;play(s,s.players[0].id,card(s,'minus3'),s.players[1].id);assert.equal(s.players[1].alive,false);assert.equal(s.turn,2)});
test('last survivor wins',()=>{const s=fixture(2);s.players[1].total=2;play(s,s.players[0].id,card(s,'minus5'),s.players[1].id);assert.equal(s.status,'finished');assert.deepEqual(s.winners,[s.players[0].id])});
test('divide rounds up and double is capped at 99',()=>{let s=fixture();s.players[0].total=7;play(s,s.players[0].id,card(s,'divide'),s.players[0].id);assert.equal(s.players[0].total,4);s=fixture();s.players[1].total=70;play(s,s.players[0].id,card(s,'double'),s.players[1].id);assert.equal(s.players[1].total,99)});
test('swap exchanges numbers but not cards; shield blocks it',()=>{let s=fixture();s.players[0].total=9;s.players[1].total=4;const hand=s.players[1].hand.map(x=>x.id);play(s,s.players[0].id,card(s,'swap'),s.players[1].id);assert.equal(s.players[0].total,4);assert.equal(s.players[1].total,9);assert.deepEqual(s.players[1].hand.map(x=>x.id),hand);s=fixture();s.players[1].shield=true;s.players[1].total=4;play(s,s.players[0].id,card(s,'swap'),s.players[1].id);assert.equal(s.players[0].total,20);assert.equal(s.players[1].total,4);assert.equal(s.players[1].shield,false)});
test('lock at zero blocks a win until their own turn ends',()=>{const s=fixture();s.players[1].locked=true;s.players[1].total=3;play(s,s.players[0].id,card(s,'minus3'),s.players[1].id);assert.equal(s.status,'playing');assert.equal(s.turn,1);play(s,s.players[1].id,card(s,'shield'),s.players[1].id);assert.equal(s.status,'finished');assert.deepEqual(s.winners,[s.players[1].id])});
test('cloak masks current total from everyone except owner',()=>{const s=fixture();const p=s.players[0];play(s,p.id,card(s,'hide'),p.id);assert.equal(view(s,s.players[1].id).players[0].total,null);assert.equal(view(s,p.id).players[0].total,20);for(let i=0;i<3;i++){const q=s.players[s.turn];play(s,q.id,card(s,'shield'),q.id)}assert.equal(s.turn,0);assert.equal(view(s,s.players[1].id).players[0].total,20)});
test('steal transfers exactly one card and never reveals others',()=>{const s=fixture();const victim=s.players[1],ids=victim.hand.map(c=>c.id);play(s,s.players[0].id,card(s,'steal'),victim.id);assert.equal(victim.hand.length,4);assert.equal(s.players[0].hand.length,1);assert.ok(ids.includes(s.players[0].hand[0].id));assert.ok(!('hand'in view(s,victim.id).players[0]))});
test('reverse changes turn direction and preserves 2-player turns',()=>{let s=fixture();play(s,s.players[0].id,card(s,'reverse'),s.players[0].id);assert.equal(s.turn,3);s=fixture(2);play(s,s.players[0].id,card(s,'reverse'),s.players[0].id);assert.equal(s.turn,1)});
test('out of turn, reused cards, missing draw and stale turn rejected',()=>{const s=fixture();const cid=card(s,'minus1');assert.throws(()=>play(s,s.players[1].id,cid,s.players[0].id),/turn/);s.phase='draw';assert.throws(()=>play(s,s.players[0].id,cid,s.players[0].id),/Draw/);assert.throws(()=>act(s,s.players[0].id,'draw',{turnId:-1}),/changed/);act(s,s.players[0].id,'draw',{turnId:s.turnId});assert.throws(()=>act(s,s.players[0].id,'draw',{turnId:s.turnId}),/already/)});
test('2v2 requires balanced teams and alternates seats',()=>{const s=fixture(4,'teams');assert.deepEqual(s.players.map(p=>p.team),[0,1,0,1]);s.status='lobby';s.players[0].team=1;assert.throws(()=>start(s),/two players/)});
test('teammate zero wins for both teammates with private hands',()=>{const s=fixture(4,'teams'),a=s.players[0],b=s.players[2];b.total=1;play(s,a.id,card(s,'minus1'),b.id);assert.deepEqual(new Set(s.winners),new Set([a.id,b.id]));assert.equal(view(s,a.id).players.filter(p=>'hand'in p).length,1)});
test('team wins if both opponents eliminated',()=>{const s=fixture(4,'teams');s.players[1].alive=false;s.players[3].total=1;play(s,s.players[0].id,card(s,'minus3'),s.players[3].id);assert.equal(s.status,'finished');assert.equal(s.winners.length,2)});
test('timeouts penalize, advance, and remove after 3 misses',()=>{const s=fixture();s.players[0].misses=2;const initial=s.players[0].total;assert.equal(timeout(s,s.deadline-1),false);assert.equal(timeout(s,s.deadline+1),true);assert.equal(s.players[0].total,initial+2);assert.equal(s.players[0].alive,false);assert.equal(s.turn,1)});
test('leaving active match forfeits and moves host',()=>{const s=fixture();const id=s.players[0].id;act(s,id,'leave');assert.equal(s.players[0].left,true);assert.equal(s.turn,1);assert.notEqual(s.host,id);assert.throws(()=>view(s,id),/not in/)});
test('rematch clears prior cards, effects and readiness',()=>{const s=fixture();s.status='finished';s.players[1].locked=true;act(s,s.host,'rematch');assert.equal(s.status,'lobby');assert.equal(s.players[1].locked,false);assert.equal(s.players[1].hand.length,0);assert.equal(s.players[1].ready,false)});
test('simulation: 2–8 player matches and 2v2 finish with invariants intact',()=>{let games=0;for(const mode of ['ffa','teams'])for(const n of mode==='teams'?[4]:[2,3,4,5,6,7,8])for(let trial=0;trial<6;trial++){
const s=fixture(n,mode);let moves=0;while(s.status==='playing'&&moves<1000){const p=s.players[s.turn];if(s.phase==='draw')act(s,p.id,'draw',{turnId:s.turnId});const choice=chooseBotMove(s,p.id);assert.ok(choice);act(s,p.id,'play',{...choice,turnId:s.turnId});assert.ok(s.players.every(p=>Number.isInteger(p.total)&&p.total<=99));assert.ok(s.players.every(p=>p.hand.length<=12));moves++}assert.equal(s.status,'finished',`unfinished ${mode}/${n}`);assert.ok(s.winners.length);games++}console.log('Completed',games,'simulated matches')});
